import { YRIPPFormData } from "@/lib/types/yripp-form";

export const createInitialFormData = (): YRIPPFormData => ({
  sectionA: {
    independentPersonName: "",
    independentPersonNumber: "",
    policeStation: "",
    interviewDate: "",
    callTime: "",
    policeContact: { rank: "", name: "", section: "", sectionOther: "" },
    arrivalTime: "",
    parentNotAttendingReason: [],
    custodyDuration: "",
    mainOffenceTypes: {
      crimesAgainstPerson: [],
      drugs: [],
      crimesAgainstProperty: [],
      other: [],
    },
    offenceOccurredInDHHS: "",
  },
  sectionBPartA: {
    preferredFirstName: "",
    immediateNeeds: [],
    satisfiedWithPoliceTreatment: "",
    policeTreatmentConcerns: [],
    actionRequired: "",
    gender: "",
    age: "",
    dateOfBirth: "",
    livingArrangement: "",
    countryOfBirth: "",
    culturalIdentity: "",
    isATSI: "",
    valsContacted: "",
    englishFirstLanguage: "",
    otherLanguages: "",
    previousPoliceInterviews: "",
    ypConcernsAboutPoliceTreatment: [],
    ypActionWanted: [],
  },
  sectionC: {
    opportunityToTalkPrivate: "",
    opportunityToTalkWithPolice: "",
    rightsExplained: [],
    rightsExplainedOptional: [],
    ypUnderstandsRights: "",
    ypSoughtRights: {
      friendOrRelative: { sought: "" },
      interpreter: { sought: "" },
      yrippLegalService: { sought: "" },
      valsLawyer: { sought: "" },
      otherLawyer: { sought: "" },
      other: { sought: "", specify: "" },
    },
    englishAdequate: "",
    interpreterContacted: "",
    fitForInterview: "",
    stepsTaken: [],
  },
  interview: {
    informant: { rank: "", badgeNumber: "", name: "" },
    corroborator: { rank: "", badgeNumber: "", name: "" },
    interviewTimes: {
      commenced: "",
      suspended: "",
      recommenced: "",
      reasonForSuspension: "",
      concluded: "",
    },
    witnessedActions: [
      { action: "fingerprinting", witnessed: "no", consent: "withoutConsent" },
      { action: "photographing", witnessed: "no", consent: "withoutConsent" },
      { action: "searching", witnessed: "no", consent: "withoutConsent" },
      { action: "dna", witnessed: "no", consent: "withoutConsent" },
    ],
  },
  outcome: {
    interviewOutcome: "",
    ypUnderstoodOutcome: "",
    bailHearingSupport: "",
    bailHearingOutcome: "",
  },
  ipConcerns: {
    hasConcerns: "",
    concernAbout: [],
  },
  sectionBPartB: {
    hasWorker: [],
    referralServices: {
      legalService: { faxed: false, card: false },
      housing: { faxed: false, card: false },
      counselling: { faxed: false, card: false },
      healthService: { faxed: false, card: false },
      drugAlcohol: { faxed: false, card: false },
      indigenous: { faxed: false, card: false },
      migrantRefugee: { faxed: false, card: false },
      genericYouth: { faxed: false, card: false },
      educationEmployment: { faxed: false, card: false },
      schoolTeacher: { faxed: false, card: false },
      disability: { faxed: false, card: false },
      other: { faxed: false, card: false },
    },
    permissionToRecordContact: "",
    happyWithTreatment: "",
    ypWantsAction: [],
  },
  sectionE: {
    spokeToSergeant: "",
    propertyReturned: "",
    concernsRaisedWithSergeant: "none",
    accommodationForNight: "",
    transportationHome: [],
    sawYpLeave: "",
    whatOccurred: [],
    interviewCancelledAfterLeftHome: false,
    interviewCancelledBeforeLeftHome: false,
    wantYRIPPFollowUp: "",
    leftStationTime: "",
  },
  sectionF: {
    additionalNotes: "",
  },
  officeUse: {
    callId: "",
    relatedCallId: "",
    directReferral: "",
    irsReceived: "",
    receivedDate: "",
    receivedBy: "",
  },
  metadata: {
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    draft: true,
    submitted: false,
  },
});
